# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49ef6a5aa3bff4baa8d01becbfd3db9f6c2dc45ea4a0c21b423ea290aef219758b786923ce269f3cb6fee5220a9f2aefed58376d8b7c403d99e52355a4534eee

test:
  secret_key_base: 0163e43f0af8003ef0413d0ccc249101f08e6033f5a61e06c0c8c5db5ffe4126a430605a7d4ef5f992aea59a2cb05e47093e8b46b732af74622129240386a78c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
